[build]
  # Your existing build configuration (if any)

[functions]
  directory = "functions"  # Path to your functions directory

[[redirects]]
  from = "/cron"  # Optional endpoint for manual triggering
  to = "/.netlify/functions/cron"
  status = 200

  # Cron trigger for the function (within the same [functions] section)
  runtime = "nodejs16"  # Adjust runtime if needed
  schedule = "@hourly"  # Replace with desired schedule
